import imgDecaf1 from '../../images/main/slider/flat_white_img1.png';
import imgDecaf2 from '../../images/main/slider/flat_white_img2.png';
import imgDecaf3 from '../../images/main/slider/flat_white_img3.png';
import imgDecaf4 from '../../images/main/slider/flat_white_img4.png';
import imgDecaf5 from '../../images/main/slider/flat_white_img5.png';
import imgDecaf6 from '../../images/main/slider/flat_white_img6.png';
import imgCatalog1 from '../../images/main/catalog/imgProduct/coffee-can-1.png';
import imgCatalog2 from '../../images/main/catalog/imgProduct/coffee-can-2.png';
import imgCatalog3 from '../../images/main/catalog/imgProduct/coffee-can-3.png';
import imgCatalog4 from '../../images/main/catalog/imgProduct/coffee-can-4.png';
import imgCatalog5 from '../../images/main/catalog/imgProduct/coffee-can-5.png';
import imgCatalog6 from '../../images/main/catalog/imgProduct/coffee-can-6.png';

export const products = [
    {
        id: 1,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '295₽',
        newPrice: '225₽',
        imgSlider: imgDecaf1,
        imgCatalog: imgCatalog1,
        milk: 'animal',
        region: 'Brazil',
    },
    {
        id: 2,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '29₽',
        newPrice: false,
        imgSlider: imgDecaf2,
        imgCatalog: imgCatalog2,
        milk: 'vegetable',
        region: 'Ethiopia',
    },
    {
        id: 3,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '295₽',
        newPrice: '350₽',
        imgSlider: imgDecaf3,
        imgCatalog: imgCatalog3,
        milk: '',
        region: 'Colombia',
    },
    {
        id: 4,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: false,
        imgSlider: imgDecaf4,
        imgCatalog: imgCatalog4,
        milk: '',
        region: 'Costa_Rica',
    },
    {
        id: 5,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '330₽',
        imgSlider: imgDecaf5,
        imgCatalog: imgCatalog5,
        milk: 'animal',
        region: '',
    },
    {
        id: 6,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '340₽',
        imgSlider: imgDecaf6,
        imgCatalog: imgCatalog6,
        milk: 'vegetable',
        region: 'Brazil',
    },
    {
        id: 7,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '295₽',
        newPrice: '225₽',
        imgSlider: imgDecaf1,
        imgCatalog: imgCatalog1,
        milk: 'animal',
        region: 'Peru',
    },
    {
        id: 8,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '30₽',
        newPrice: false,
        imgSlider: imgDecaf2,
        imgCatalog: imgCatalog2,
        milk: 'vegetable',
        region: 'Ethiopia',
    },
    {
        id: 9,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '295₽',
        newPrice: '350₽',
        imgSlider: imgDecaf3,
        imgCatalog: imgCatalog3,
        milk: '',
        region: 'Colombia',
    },
    {
        id: 10,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: false,
        imgSlider: imgDecaf4,
        imgCatalog: imgCatalog4,
        milk: '',
        region: 'Costa_Rica',
    },
    {
        id: 11,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '330₽',
        imgSlider: imgDecaf5,
        imgCatalog: imgCatalog5,
        milk: 'animal',
        region: '',
    },
    {
        id: 12,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '340₽',
        imgSlider: imgDecaf6,
        imgCatalog: imgCatalog6,
        milk: 'vegetable',
        region: 'Brazil',
    },
    {
        id: 13,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '295₽',
        newPrice: '225₽',
        imgSlider: imgDecaf1,
        imgCatalog: imgCatalog1,
        milk: 'animal',
        region: 'Brazil',
    },
    {
        id: 14,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '29₽',
        newPrice: false,
        imgSlider: imgDecaf2,
        imgCatalog: imgCatalog2,
        milk: 'vegetable',
        region: 'Ethiopia',
    },
    {
        id: 15,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '295₽',
        newPrice: '350₽',
        imgSlider: imgDecaf3,
        imgCatalog: imgCatalog3,
        milk: '',
        region: 'Colombia',
    },
    {
        id: 16,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: false,
        imgSlider: imgDecaf4,
        imgCatalog: imgCatalog4,
        milk: '',
        region: 'Costa_Rica',
    },
    {
        id: 17,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '330₽',
        imgSlider: imgDecaf5,
        imgCatalog: imgCatalog5,
        milk: 'animal',
        region: '',
    },
    {
        id: 18,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '340₽',
        imgSlider: imgDecaf6,
        imgCatalog: imgCatalog6,
        milk: 'vegetable',
        region: 'Brazil',
    },
    {
        id: 19,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '295₽',
        newPrice: '225₽',
        imgSlider: imgDecaf1,
        imgCatalog: imgCatalog1,
        milk: 'animal',
        region: 'Peru',
    },
    {
        id: 20,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '29₽',
        newPrice: false,
        imgSlider: imgDecaf2,
        imgCatalog: imgCatalog2,
        milk: 'vegetable',
        region: 'Ethiopia',
    },
    {
        id: 21,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '295₽',
        newPrice: '350₽',
        imgSlider: imgDecaf3,
        imgCatalog: imgCatalog3,
        milk: '',
        region: 'Colombia',
    },
    {
        id: 22,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: false,
        imgSlider: imgDecaf4,
        imgCatalog: imgCatalog4,
        milk: '',
        region: 'Costa_Rica',
    },
    {
        id: 23,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '330₽',
        imgSlider: imgDecaf5,
        imgCatalog: imgCatalog5,
        milk: 'animal',
        region: '',
    },
    {
        id: 24,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '340₽',
        imgSlider: imgDecaf6,
        imgCatalog: imgCatalog6,
        milk: 'vegetable',
        region: 'Brazil',
    },
    {
        id: 25,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '330₽',
        imgSlider: imgDecaf5,
        imgCatalog: imgCatalog5,
        milk: 'animal',
        region: '',
    },
    {
        id: 26,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '340₽',
        imgSlider: imgDecaf6,
        imgCatalog: imgCatalog6,
        milk: 'vegetable',
        region: 'Brazil',
    },
    {
        id: 27,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '295₽',
        newPrice: '225₽',
        imgSlider: imgDecaf1,
        imgCatalog: imgCatalog1,
        milk: 'animal',
        region: 'Brazil',
    },
    {
        id: 28,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '29₽',
        newPrice: false,
        imgSlider: imgDecaf2,
        imgCatalog: imgCatalog2,
        milk: 'vegetable',
        region: 'Ethiopia',
    },
    {
        id: 29,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '295₽',
        newPrice: '350₽',
        imgSlider: imgDecaf3,
        imgCatalog: imgCatalog3,
        milk: '',
        region: 'Colombia',
    },
    {
        id: 30,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: false,
        imgSlider: imgDecaf4,
        imgCatalog: imgCatalog4,
        milk: '',
        region: 'Costa_Rica',
    },
    {
        id: 31,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '330₽',
        imgSlider: imgDecaf5,
        imgCatalog: imgCatalog5,
        milk: 'animal',
        region: '',
    },
    {
        id: 32,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '340₽',
        imgSlider: imgDecaf6,
        imgCatalog: imgCatalog6,
        milk: 'vegetable',
        region: 'Brazil',
    },
    {
        id: 33,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '295₽',
        newPrice: '225₽',
        imgSlider: imgDecaf1,
        imgCatalog: imgCatalog1,
        milk: 'animal',
        region: 'Peru',
    },
    {
        id: 34,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '30₽',
        newPrice: false,
        imgSlider: imgDecaf2,
        imgCatalog: imgCatalog2,
        milk: 'vegetable',
        region: 'Ethiopia',
    },
    {
        id: 35,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '295₽',
        newPrice: '350₽',
        imgSlider: imgDecaf3,
        imgCatalog: imgCatalog3,
        milk: '',
        region: 'Colombia',
    },
    {
        id: 36,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: false,
        imgSlider: imgDecaf4,
        imgCatalog: imgCatalog4,
        milk: '',
        region: 'Costa_Rica',
    },
    {
        id: 37,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '330₽',
        imgSlider: imgDecaf5,
        imgCatalog: imgCatalog5,
        milk: 'animal',
        region: '',
    },
    {
        id: 38,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '340₽',
        imgSlider: imgDecaf6,
        imgCatalog: imgCatalog6,
        milk: 'vegetable',
        region: 'Brazil',
    },
    {
        id: 39,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '295₽',
        newPrice: '225₽',
        imgSlider: imgDecaf1,
        imgCatalog: imgCatalog1,
        milk: 'animal',
        region: 'Brazil',
    },
    {
        id: 40,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '29₽',
        newPrice: false,
        imgSlider: imgDecaf2,
        imgCatalog: imgCatalog2,
        milk: 'vegetable',
        region: 'Ethiopia',
    },
    {
        id: 41,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '295₽',
        newPrice: '350₽',
        imgSlider: imgDecaf3,
        imgCatalog: imgCatalog3,
        milk: '',
        region: 'Colombia',
    },
    {
        id: 42,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: false,
        imgSlider: imgDecaf4,
        imgCatalog: imgCatalog4,
        milk: '',
        region: 'Costa_Rica',
    },
    {
        id: 43,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '330₽',
        imgSlider: imgDecaf5,
        imgCatalog: imgCatalog5,
        milk: 'animal',
        region: '',
    },
    {
        id: 44,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '340₽',
        imgSlider: imgDecaf6,
        imgCatalog: imgCatalog6,
        milk: 'vegetable',
        region: 'Brazil',
    },
    {
        id: 45,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '295₽',
        newPrice: '225₽',
        imgSlider: imgDecaf1,
        imgCatalog: imgCatalog1,
        milk: 'animal',
        region: 'Peru',
    },
    {
        id: 46,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '29₽',
        newPrice: false,
        imgSlider: imgDecaf2,
        imgCatalog: imgCatalog2,
        milk: 'vegetable',
        region: 'Ethiopia',
    },
    {
        id: 47,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '295₽',
        newPrice: '350₽',
        imgSlider: imgDecaf3,
        imgCatalog: imgCatalog3,
        milk: '',
        region: 'Colombia',
    },
    {
        id: 48,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: false,
        imgSlider: imgDecaf4,
        imgCatalog: imgCatalog4,
        milk: '',
        region: 'Costa_Rica',
    },
    {
        id: 49,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '330₽',
        imgSlider: imgDecaf5,
        imgCatalog: imgCatalog5,
        milk: 'animal',
        region: '',
    },
    {
        id: 50,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '340₽',
        imgSlider: imgDecaf6,
        imgCatalog: imgCatalog6,
        milk: 'vegetable',
        region: 'Brazil',
    },
    {
        id: 51,
        news: false,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '330₽',
        imgSlider: imgDecaf5,
        imgCatalog: imgCatalog5,
        milk: 'animal',
        region: '',
    },
    {
        id: 52,
        news: true,
        title: 'Декаф Флэт Уайт',
        textSlider: 'Свежесваренный кофе без кофеина из Эфиопии с натуральным фермерским молоком — то, что нужно для расслабления после тяжёлого рабочего дня',
        textCatalog: 'Кофе без кофеина из Эфиопии с натуральным фермерским молоком',
        price: '350₽',
        newPrice: '340₽',
        imgSlider: imgDecaf6,
        imgCatalog: imgCatalog6,
        milk: 'vegetable',
        region: 'Brazil',
    },
]